//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Cbddo.eYazisma.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:ParafOzeti-2")]
    [System.Xml.Serialization.XmlRootAttribute("ParafOzeti", Namespace="urn:dpt:eyazisma:schema:xsd:ParafOzeti-2", IsNullable=false)]
    public partial class CT_ParafOzeti {
        
        private CT_Reference[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", Order=0)]
        public CT_Reference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", IsNullable=false)]
    public partial class CT_Reference {
        
        private CT_DigestItem digestItemField;
        
        private CT_DigestItem digestItem1Field;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_DigestItem DigestItem {
            get {
                return this.digestItemField;
            }
            set {
                this.digestItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DigestItem", Order=1)]
        public CT_DigestItem DigestItem1 {
            get {
                return this.digestItem1Field;
            }
            set {
                this.digestItem1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2")]
    [System.Xml.Serialization.XmlRootAttribute("DigestItem", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", IsNullable=false)]
    public partial class CT_DigestItem {
        
        private CT_DigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_DigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2")]
    [System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", IsNullable=false)]
    public partial class CT_DigestMethod {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:BelgeHedef-2")]
    [System.Xml.Serialization.XmlRootAttribute("BelgeHedef", Namespace="urn:dpt:eyazisma:schema:xsd:BelgeHedef-2", IsNullable=false)]
    public partial class CT_BelgeHedef {
        
        private CT_Hedef[] hedefListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Hedef", IsNullable=false)]
        public CT_Hedef[] HedefListesi {
            get {
                return this.hedefListesiField;
            }
            set {
                this.hedefListesiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Hedef {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GercekSahis", typeof(CT_GercekSahis), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KurumKurulus", typeof(CT_KurumKurulus), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TuzelSahis", typeof(CT_TuzelSahis), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_GercekSahis {
        
        private CT_Kisi kisiField;
        
        private string tCKNField;
        
        private TextType gorevField;
        
        private CT_IletisimBilgisi iletisimBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_Kisi Kisi {
            get {
                return this.kisiField;
            }
            set {
                this.kisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string TCKN {
            get {
                return this.tCKNField;
            }
            set {
                this.tCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TextType Gorev {
            get {
                return this.gorevField;
            }
            set {
                this.gorevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CT_IletisimBilgisi IletisimBilgisi {
            get {
                return this.iletisimBilgisiField;
            }
            set {
                this.iletisimBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Kisi {
        
        private NameType ilkAdiField;
        
        private NameType soyadiField;
        
        private NameType ikinciAdiField;
        
        private NameType unvanField;
        
        private TextType onEkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NameType IlkAdi {
            get {
                return this.ilkAdiField;
            }
            set {
                this.ilkAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameType Soyadi {
            get {
                return this.soyadiField;
            }
            set {
                this.soyadiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NameType IkinciAdi {
            get {
                return this.ikinciAdiField;
            }
            set {
                this.ikinciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NameType Unvan {
            get {
                return this.unvanField;
            }
            set {
                this.unvanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TextType OnEk {
            get {
                return this.onEkField;
            }
            set {
                this.onEkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2")]
    public partial class NameType {
        
        private string languageIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2")]
    [System.Xml.Serialization.XmlRootAttribute("Konu", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class TextType {
        
        private string languageIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_IletisimBilgisi {
        
        private string telefonField;
        
        private string telefonDigerField;
        
        private string ePostaField;
        
        private string kepAdresiField;
        
        private string faksField;
        
        private string webAdresiField;
        
        private TextType adresField;
        
        private NameType ilField;
        
        private NameType ilceField;
        
        private NameType ulkeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TelefonDiger {
            get {
                return this.telefonDigerField;
            }
            set {
                this.telefonDigerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EPosta {
            get {
                return this.ePostaField;
            }
            set {
                this.ePostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KepAdresi {
            get {
                return this.kepAdresiField;
            }
            set {
                this.kepAdresiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Faks {
            get {
                return this.faksField;
            }
            set {
                this.faksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string WebAdresi {
            get {
                return this.webAdresiField;
            }
            set {
                this.webAdresiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TextType Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public NameType Il {
            get {
                return this.ilField;
            }
            set {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public NameType Ilce {
            get {
                return this.ilceField;
            }
            set {
                this.ilceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public NameType Ulke {
            get {
                return this.ulkeField;
            }
            set {
                this.ulkeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_KurumKurulus {
        
        private string kKKField;
        
        private NameType adiField;
        
        private CT_IletisimBilgisi iletisimBilgisiField;
        
        private string birimKKKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string KKK {
            get {
                return this.kKKField;
            }
            set {
                this.kKKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameType Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CT_IletisimBilgisi IletisimBilgisi {
            get {
                return this.iletisimBilgisiField;
            }
            set {
                this.iletisimBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string BirimKKK {
            get {
                return this.birimKKKField;
            }
            set {
                this.birimKKKField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_TuzelSahis {
        
        private IdentifierType idField;
        
        private NameType adiField;
        
        private CT_IletisimBilgisi iletisimBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameType Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CT_IletisimBilgisi IletisimBilgisi {
            get {
                return this.iletisimBilgisiField;
            }
            set {
                this.iletisimBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2")]
    [System.Xml.Serialization.XmlRootAttribute("OzId", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class IdentifierType {
        
        private string schemeIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:NihaiOzet-2")]
    [System.Xml.Serialization.XmlRootAttribute("NihaiOzet", Namespace="urn:dpt:eyazisma:schema:xsd:NihaiOzet-2", IsNullable=false)]
    public partial class CT_NihaiOzet {
        
        private CT_Reference[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", Order=0)]
        public CT_Reference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:NihaiUstveri-2")]
    [System.Xml.Serialization.XmlRootAttribute("NihaiUstVeri", Namespace="urn:dpt:eyazisma:schema:xsd:NihaiUstveri-2", IsNullable=false)]
    public partial class CT_NihaiUstveri {
        
        private System.DateTime tarihField;
        
        private string belgeNoField;
        
        private CT_Imza[] belgeImzalarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=0)]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=1)]
        public string BelgeNo {
            get {
                return this.belgeNoField;
            }
            set {
                this.belgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Imza", IsNullable=false)]
        public CT_Imza[] BelgeImzalar {
            get {
                return this.belgeImzalarField;
            }
            set {
                this.belgeImzalarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Imza {
        
        private CT_GercekSahis imzalayanField;
        
        private CT_GercekSahis yetkiDevredenField;
        
        private CT_GercekSahis vekaletVerenField;
        
        private NameType makamField;
        
        private TextType amacField;
        
        private TextType aciklamaField;
        
        private System.DateTime tarihField;
        
        private bool tarihFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_GercekSahis Imzalayan {
            get {
                return this.imzalayanField;
            }
            set {
                this.imzalayanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CT_GercekSahis YetkiDevreden {
            get {
                return this.yetkiDevredenField;
            }
            set {
                this.yetkiDevredenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CT_GercekSahis VekaletVeren {
            get {
                return this.vekaletVerenField;
            }
            set {
                this.vekaletVerenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NameType Makam {
            get {
                return this.makamField;
            }
            set {
                this.makamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TextType Amac {
            get {
                return this.amacField;
            }
            set {
                this.amacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TextType Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TarihSpecified {
            get {
                return this.tarihFieldSpecified;
            }
            set {
                this.tarihFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Ustveri-2")]
    [System.Xml.Serialization.XmlRootAttribute("UstVeri", Namespace="urn:dpt:eyazisma:schema:xsd:Ustveri-2", IsNullable=false)]
    public partial class CT_Ustveri {
        
        private string belgeIdField;
        
        private TextType konuField;
        
        private ST_KodGuvenlikKodu guvenlikKoduField;
        
        private System.Nullable<System.DateTime> guvenlikKoduGecerlilikTarihiField;
        
        private bool guvenlikKoduGecerlilikTarihiFieldSpecified;
        
        private string mimeTuruField;
        
        private IdentifierType ozIdField;
        
        private CT_Dagitim[] dagitimListesiField;
        
        private CT_Ek[] eklerField;
        
        private CT_Ilgi[] ilgilerField;
        
        private string dilField;
        
        private CT_Olusturan olusturanField;
        
        private CT_Ilgili[] ilgiliListesiField;
        
        private string dosyaAdiField;
        
        private CT_SDPBilgisi sdpBilgisiField;
        
        private CT_HEYSK[] heyskListesiField;
        
        private CT_DogrulamaBilgisi dogrulamaBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", DataType="normalizedString", Order=0)]
        public string BelgeId {
            get {
                return this.belgeIdField;
            }
            set {
                this.belgeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=1)]
        public TextType Konu {
            get {
                return this.konuField;
            }
            set {
                this.konuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=2)]
        public ST_KodGuvenlikKodu GuvenlikKodu {
            get {
                return this.guvenlikKoduField;
            }
            set {
                this.guvenlikKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> GuvenlikKoduGecerlilikTarihi {
            get {
                return this.guvenlikKoduGecerlilikTarihiField;
            }
            set {
                this.guvenlikKoduGecerlilikTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GuvenlikKoduGecerlilikTarihiSpecified {
            get {
                return this.guvenlikKoduGecerlilikTarihiFieldSpecified;
            }
            set {
                this.guvenlikKoduGecerlilikTarihiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", DataType="normalizedString", IsNullable=true, Order=4)]
        public string MimeTuru {
            get {
                return this.mimeTuruField;
            }
            set {
                this.mimeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=5)]
        public IdentifierType OzId {
            get {
                return this.ozIdField;
            }
            set {
                this.ozIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Dagitim", IsNullable=false)]
        public CT_Dagitim[] DagitimListesi {
            get {
                return this.dagitimListesiField;
            }
            set {
                this.dagitimListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ek", IsNullable=false)]
        public CT_Ek[] Ekler {
            get {
                return this.eklerField;
            }
            set {
                this.eklerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ilgi", IsNullable=false)]
        public CT_Ilgi[] Ilgiler {
            get {
                return this.ilgilerField;
            }
            set {
                this.ilgilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=9)]
        public string Dil {
            get {
                return this.dilField;
            }
            set {
                this.dilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=10)]
        public CT_Olusturan Olusturan {
            get {
                return this.olusturanField;
            }
            set {
                this.olusturanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ilgili", IsNullable=false)]
        public CT_Ilgili[] IlgiliListesi {
            get {
                return this.ilgiliListesiField;
            }
            set {
                this.ilgiliListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=12)]
        public string DosyaAdi {
            get {
                return this.dosyaAdiField;
            }
            set {
                this.dosyaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=13)]
        public CT_SDPBilgisi SdpBilgisi {
            get {
                return this.sdpBilgisiField;
            }
            set {
                this.sdpBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Heysk", IsNullable=false)]
        public CT_HEYSK[] HeyskListesi {
            get {
                return this.heyskListesiField;
            }
            set {
                this.heyskListesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", Order=15)]
        public CT_DogrulamaBilgisi DogrulamaBilgisi {
            get {
                return this.dogrulamaBilgisiField;
            }
            set {
                this.dogrulamaBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:KodGuvenlik-2")]
    [System.Xml.Serialization.XmlRootAttribute("GuvenlikKodu", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public enum ST_KodGuvenlikKodu {
        
        /// <remarks/>
        YOK,
        
        /// <remarks/>
        HZO,
        
        /// <remarks/>
        OZL,
        
        /// <remarks/>
        GZL,
        
        /// <remarks/>
        CGZ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Dagitim {
        
        private object itemField;
        
        private ST_KodIvedilik ivedilikField;
        
        private ST_KodDagitimTuru dagitimTuruField;
        
        private string miatField;
        
        private CT_KonulmamisEk[] konulmamisEkListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GercekSahis", typeof(CT_GercekSahis), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KurumKurulus", typeof(CT_KurumKurulus), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TuzelSahis", typeof(CT_TuzelSahis), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ST_KodIvedilik Ivedilik {
            get {
                return this.ivedilikField;
            }
            set {
                this.ivedilikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ST_KodDagitimTuru DagitimTuru {
            get {
                return this.dagitimTuruField;
            }
            set {
                this.dagitimTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=3)]
        public string Miat {
            get {
                return this.miatField;
            }
            set {
                this.miatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KonulmamisEk", IsNullable=false)]
        public CT_KonulmamisEk[] KonulmamisEkListesi {
            get {
                return this.konulmamisEkListesiField;
            }
            set {
                this.konulmamisEkListesiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:KodIvedilik-2")]
    public enum ST_KodIvedilik {
        
        /// <remarks/>
        NRM,
        
        /// <remarks/>
        ACL,
        
        /// <remarks/>
        GNL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:KodDagitimTuru-2")]
    public enum ST_KodDagitimTuru {
        
        /// <remarks/>
        BLG,
        
        /// <remarks/>
        GRG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_KonulmamisEk {
        
        private string ekIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string EkId {
            get {
                return this.ekIdField;
            }
            set {
                this.ekIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Ek {
        
        private CT_Id idField;
        
        private string belgeNoField;
        
        private ST_KodEkTuru turField;
        
        private string dosyaAdiField;
        
        private string mimeTuruField;
        
        private TextType adField;
        
        private int siraNoField;
        
        private TextType aciklamaField;
        
        private string referansField;
        
        private IdentifierType ozIdField;
        
        private bool imzaliMiField;
        
        private bool imzaliMiFieldSpecified;
        
        private CT_Ozet ozetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BelgeNo {
            get {
                return this.belgeNoField;
            }
            set {
                this.belgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ST_KodEkTuru Tur {
            get {
                return this.turField;
            }
            set {
                this.turField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DosyaAdi {
            get {
                return this.dosyaAdiField;
            }
            set {
                this.dosyaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string MimeTuru {
            get {
                return this.mimeTuruField;
            }
            set {
                this.mimeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TextType Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int SiraNo {
            get {
                return this.siraNoField;
            }
            set {
                this.siraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TextType Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=8)]
        public string Referans {
            get {
                return this.referansField;
            }
            set {
                this.referansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public IdentifierType OzId {
            get {
                return this.ozIdField;
            }
            set {
                this.ozIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool ImzaliMi {
            get {
                return this.imzaliMiField;
            }
            set {
                this.imzaliMiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImzaliMiSpecified {
            get {
                return this.imzaliMiFieldSpecified;
            }
            set {
                this.imzaliMiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CT_Ozet Ozet {
            get {
                return this.ozetField;
            }
            set {
                this.ozetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Id {
        
        private string valueField;
        
        private bool eYazismaIdMiField;
        
        private bool eYazismaIdMiFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EYazismaIdMi {
            get {
                return this.eYazismaIdMiField;
            }
            set {
                this.eYazismaIdMiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EYazismaIdMiSpecified {
            get {
                return this.eYazismaIdMiFieldSpecified;
            }
            set {
                this.eYazismaIdMiFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:KodEkTuru-2")]
    public enum ST_KodEkTuru {
        
        /// <remarks/>
        DED,
        
        /// <remarks/>
        HRF,
        
        /// <remarks/>
        FZK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Ozet {
        
        private CT_OzetAlgoritmasi ozetAlgoritmasiField;
        
        private byte[] ozetDegeriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_OzetAlgoritmasi OzetAlgoritmasi {
            get {
                return this.ozetAlgoritmasiField;
            }
            set {
                this.ozetAlgoritmasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] OzetDegeri {
            get {
                return this.ozetDegeriField;
            }
            set {
                this.ozetDegeriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_OzetAlgoritmasi {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Ilgi {
        
        private CT_Id idField;
        
        private string belgeNoField;
        
        private System.DateTime tarihField;
        
        private bool tarihFieldSpecified;
        
        private string etiketField;
        
        private string ekIdField;
        
        private TextType adField;
        
        private TextType aciklamaField;
        
        private IdentifierType ozIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_Id Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BelgeNo {
            get {
                return this.belgeNoField;
            }
            set {
                this.belgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TarihSpecified {
            get {
                return this.tarihFieldSpecified;
            }
            set {
                this.tarihFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Etiket {
            get {
                return this.etiketField;
            }
            set {
                this.etiketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string EkId {
            get {
                return this.ekIdField;
            }
            set {
                this.ekIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TextType Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TextType Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public IdentifierType OzId {
            get {
                return this.ozIdField;
            }
            set {
                this.ozIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("Olusturan", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_Olusturan {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GercekSahis", typeof(CT_GercekSahis), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KurumKurulus", typeof(CT_KurumKurulus), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TuzelSahis", typeof(CT_TuzelSahis), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_Ilgili {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GercekSahis", typeof(CT_GercekSahis), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KurumKurulus", typeof(CT_KurumKurulus), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TuzelSahis", typeof(CT_TuzelSahis), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("SdpBilgisi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_SDPBilgisi {
        
        private CT_SDP anaSdpField;
        
        private CT_SDP[] digerSdplerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CT_SDP AnaSdp {
            get {
                return this.anaSdpField;
            }
            set {
                this.anaSdpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SdpListesi", IsNullable=false)]
        public CT_SDP[] DigerSdpler {
            get {
                return this.digerSdplerField;
            }
            set {
                this.digerSdplerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_SDP {
        
        private string kodField;
        
        private string adField;
        
        private string aciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    public partial class CT_HEYSK {
        
        private int kodField;
        
        private string adField;
        
        private string tanimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tanim {
            get {
                return this.tanimField;
            }
            set {
                this.tanimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("DogrulamaBilgisi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_DogrulamaBilgisi {
        
        private string dogrulamaAdresiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DogrulamaAdresi {
            get {
                return this.dogrulamaAdresiField;
            }
            set {
                this.dogrulamaAdresiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2")]
    [System.Xml.Serialization.XmlRootAttribute("PaketOzeti", Namespace="urn:dpt:eyazisma:schema:xsd:PaketOzeti-2", IsNullable=false)]
    public partial class CT_PaketOzeti {
        
        private CT_Reference[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=0)]
        public CT_Reference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("DagitimListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_DagitimListesi {
        
        private CT_Dagitim[] dagitimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dagitim", Order=0)]
        public CT_Dagitim[] Dagitim {
            get {
                return this.dagitimField;
            }
            set {
                this.dagitimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("HedefListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_HedefListesi {
        
        private CT_Hedef[] hedefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hedef", Order=0)]
        public CT_Hedef[] Hedef {
            get {
                return this.hedefField;
            }
            set {
                this.hedefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("Ekler", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_Ekler {
        
        private CT_Ek[] ekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ek", Order=0)]
        public CT_Ek[] Ek {
            get {
                return this.ekField;
            }
            set {
                this.ekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("Ilgiler", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_Ilgiler {
        
        private CT_Ilgi[] ilgiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ilgi", Order=0)]
        public CT_Ilgi[] Ilgi {
            get {
                return this.ilgiField;
            }
            set {
                this.ilgiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("ImzaListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_ImzaListesi {
        
        private CT_Imza[] imzaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Imza", Order=0)]
        public CT_Imza[] Imza {
            get {
                return this.imzaField;
            }
            set {
                this.imzaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("HeyskListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_HEYSKListesi {
        
        private CT_HEYSK[] heyskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Heysk", Order=0)]
        public CT_HEYSK[] Heysk {
            get {
                return this.heyskField;
            }
            set {
                this.heyskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("IlgiliListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_IlgiliListesi {
        
        private CT_Ilgili[] ilgiliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ilgili", Order=0)]
        public CT_Ilgili[] Ilgili {
            get {
                return this.ilgiliField;
            }
            set {
                this.ilgiliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("KonulmamisEkListesi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_KonulmamisEkListesi {
        
        private CT_KonulmamisEk[] konulmamisEkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KonulmamisEk", Order=0)]
        public CT_KonulmamisEk[] KonulmamisEk {
            get {
                return this.konulmamisEkField;
            }
            set {
                this.konulmamisEkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("BelgeImzalar", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_BelgeImza {
        
        private CT_Imza[] imzaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Imza", Order=0)]
        public CT_Imza[] Imza {
            get {
                return this.imzaField;
            }
            set {
                this.imzaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("SifreliIcerikBilgisi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_SifreliIcerikBilgisi {
        
        private string[] uRIField;
        
        private string idField;
        
        private string versionField;
        
        private string yontemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URI", DataType="anyURI", Order=0)]
        public string[] URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Yontem {
            get {
                return this.yontemField;
            }
            set {
                this.yontemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:GuncellemeTuru-2")]
    [System.Xml.Serialization.XmlRootAttribute("GuncellemeTuru", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public enum ST_GuncellemeTuru {
        
        /// <remarks/>
        GuvenlikKodu,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("GuncellemeBilgisi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_GuncellemeBilgisi {
        
        private CT_Guncelleme[] guncellemelerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Guncellemeler", Order=0)]
        public CT_Guncelleme[] Guncellemeler {
            get {
                return this.guncellemelerField;
            }
            set {
                this.guncellemelerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("Guncelleme", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_Guncelleme {
        
        private ST_GuncellemeTuru guncellemeTuruField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST_GuncellemeTuru GuncellemeTuru {
            get {
                return this.guncellemeTuruField;
            }
            set {
                this.guncellemeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("GuvenlikKoduDegisiklikBilgisi", typeof(CT_GuvenlikKoduDegisiklikBilgisi), Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2")]
    [System.Xml.Serialization.XmlRootAttribute("GuvenlikKoduDegisiklikBilgisi", Namespace="urn:dpt:eyazisma:schema:xsd:Tipler-2", IsNullable=false)]
    public partial class CT_GuvenlikKoduDegisiklikBilgisi {
        
        private ST_KodGuvenlikKodu yeniGizlilikDerecesiField;
        
        private System.DateTime degistirmeTarihiField;
        
        private string aciklamaField;
        
        private string komisyonKarariBelgeNoField;
        
        private string komisyonKarariBelgeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ST_KodGuvenlikKodu YeniGizlilikDerecesi {
            get {
                return this.yeniGizlilikDerecesiField;
            }
            set {
                this.yeniGizlilikDerecesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DegistirmeTarihi {
            get {
                return this.degistirmeTarihiField;
            }
            set {
                this.degistirmeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KomisyonKarariBelgeNo {
            get {
                return this.komisyonKarariBelgeNoField;
            }
            set {
                this.komisyonKarariBelgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string KomisyonKarariBelgeId {
            get {
                return this.komisyonKarariBelgeIdField;
            }
            set {
                this.komisyonKarariBelgeIdField = value;
            }
        }
    }
}
